### Notes for Data Manipulation

*Tensors* are better than *numpy* arrays, since they support GPU-based computations and automatic differentiation.

1-D Tensor is called a vector, 2-D Tensor is called a Matrix, and for n-d tensor, we call them kth order tensor.

arange(n) creates a tensor with values [0, n), and unless tensors are moved to GPU manually, they are designated for CPU level computations.


In [15]:
import torch

In [16]:
x = torch.arange(15, dtype = torch.float32)
print ("Tensor: {}".format(x))
print ("Num of elements in the tensor: {}".format(x.numel()))
print ("Shape of tensors: {}".format(x.shape))

Tensor: tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14.])
Num of elements in the tensor: 15
Shape of tensors: torch.Size([15])


In [17]:
# first param is number of rows, and second param is number of columns
x = x.reshape(3, 5)
x

# To automatically assume the other shape, you can pass -1 to the unknown value and it will still do the same.
x = torch.arange(20, dtype = torch.float32)
print (x.reshape(-1, 5))
print (x.reshape(4, -1))

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])


In [18]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
# randn creates a tensor with mean 0 and unit standard deviation, use: torch.randn(shape)
torch.randn((3, 4))

tensor([[-0.5914, -1.4166,  0.6037,  0.7744],
        [-0.5299,  2.3907,  0.7442,  1.0705],
        [ 0.3021,  0.8347, -0.8330,  0.2345]])

In [22]:
num_list = [[1, 2, 3, 4], [4, 3, 2, 1], [2, 1, 3, 4]]
num_tensor = torch.tensor(num_list, dtype = torch.long)
num_tensor

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1],
        [2, 1, 3, 4]])

In [27]:
X = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# When slicing a kth-order tensor, if only 1 index is provided, it slices alongside the 0th axis
print ("X[-1]: {}".format(X[-1]))
print ("X[1:3]: {}".format(X[1:3]))

X[1, 2] = 17
X

X[-1]: tensor([ 9, 10, 11, 12])
X[1:3]: tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


tensor([[ 1,  2,  3,  4],
        [ 5,  6, 17,  8],
        [ 9, 10, 11, 12]])

In [29]:
# For first two rows, but all columns
X[:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 9, 10, 11, 12]])

In [30]:
# Element wise operations
torch.exp(X)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  8103.0840,  22026.4648,  59874.1406, 162754.7969]])

In [33]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 1, 2])

# Element wise addition, subtraction, multiplication, division and exponentiation
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  5., 10.]),
 tensor([-1.,  0.,  3.,  6.]),
 tensor([ 2.,  4.,  4., 16.]),
 tensor([0.5000, 1.0000, 4.0000, 4.0000]),
 tensor([ 1.,  4.,  4., 64.]))

In [34]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [35]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [38]:
# Dimension 0, concatenation of rows, and Dimension 1 is concatenation along columns
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [39]:
# Sum up of elements
X.sum()

tensor(66.)

In [40]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [41]:
# a is a 3 x 1 matrix, and b is a 2 x 1 matrix
# a is broadcasted in terms of columns and it becomes [[0, 0], [1, 1], [2, 2]]
# b is broadcasted in terms of rows and it becomes [[0, 1], [0, 1], [0, 1]]
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [42]:
# in place updates saves memory, as it does not allocate a new memory place for the newly created objects

before = id(Y)
Y = Y + X
id(Y) == before

False

In [43]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 136378351970368
id(Z): 136378351970368


In [44]:
before = id(X)
X += Y
id(X) == before

True

In [45]:
before = id(X)
# same operation as earlier, just implemented in a different way.
X = X + Y
id(X) == before

False

In [46]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [47]:
# only for size-1 tensors to Python scalars
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)